search as component, add to listings page
Vaccine-Hunters-Canada/VaxFinder-Frontend pull request #90
Opened 2021-05-22 16:31 UTC by shapesandobjects

2021-05-22 22:33 UTC, chrisahardie commented on src/containers/PharmacyList/PharmacyList.tsx
> +      <section aria-label="search" style={{ marginBottom: "2rem" }}>
Very minor, but there is an inconsistency in that this `section` element isn't in the `Home` component. If it should always be included, it should probably be in the `SearchCard` component.

2021-05-22 22:36 UTC, chrisahardie commented on src/components/SearchCard/SearchCard.tsx
> +          <Form onSubmit={handleSubmit}>
Hmm, there is a `role="search"` attribute value we could apply to search forms as an assistive cue, but it looks like the `Form` component doesn't support aria props... The `Form` props should probably extend from `IntrinsicAttributes` so as to support attributes assignable to HTML elements.

2021-05-22 22:36 UTC, chrisahardie submitted a review, later dismissed

2021-05-23 16:57 UTC, ericherscovich requested changes
When there are no pharmacies available, the search bar doesn't show up. Look K2T 0E5 which has no availabilities and you'll see this.

Edit: Fixed it.

2021-05-24 02:25 UTC, ericherscovich approved these changes

2021-05-24 02:51 UTC, ericherscovich commented
Added the 3 digit postal regex to this. Closes #84

2021-05-26 16:22 UTC, ericherscovich approved these changes

2021-05-26 16:22 UTC, merged